title: Getting Started with Textual Data
author: Tyler Shoemaker and Carl Stahmer
copyright: "2021"
logo: img/datalab-logo-full-color-rgb.png
only_build_toc_files: true

repository:
  url: https://github.com/ucdavisdatalab/workshop_getting_started_with_textual_data

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution

execute:
  execute_notebooks: auto

html:
  use_repository_button: true